# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-10 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190610_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='desc',
        ),
    ]
