# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-12 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_article_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='alias',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
