# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_tag_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default=123, max_length=32),
            preserve_default=False,
        ),
    ]
